### ISSUE TITLE
Incompatibility with clojure.edn when reading multiple objects from the same stream

### ISSUE THREAD

**Issue by hiredman** [tonsky/fast-edn#1]
```clj
(require '[clojure.edn :as edn]
         '[fast-edn.core :as fedn])

(def s0 (java.io.PushbackReader. (java.io.StringReader. "{:a 1}{:b 2}")) )

(edn/read s0)

(edn/read s0)

(def s1 (java.io.PushbackReader. (java.io.StringReader. "{:a 1}{:b 2}")) )

(fedn/read s1)

(fedn/read s1)
```

edn/read reads both objectes, fedn/read throws on the second call

**Comment by tonsky** [comment]
Oh right. Not a drop-in replacement then :)

**Comment by hiredman** [comment]
to be clear, this is a great project, and I have no immediate need for this feature. I just saw "Fast EDN is 100% compatible with clojure.edn" in the README and had a knee-jerk "I bet it's not" reaction, and I know various bits of performance work on data.json has broken this kind of thing between versions.

**Comment by tonsky** [comment]
It’s fine, I get it. I completely forgot about that use-case. It can be done in fast-edn but API is slightly different. It’s good to catch these things early though, thanks for pointing it out!
